### ISSUE TITLE
Translations possible?

### ISSUE THREAD

**Issue by UweKeim** [thirstyape/Easy-Password-Validator#1]
Any chance to somehow provide translations of the error messages to German?

Either during runtime or as an addition to your library?

**Comment by thirstyape** [comment]
Hi Uwe, I think adding support for error messages in other languages would be great. If you can help with the translation of the current messages to German that would be helpful. 

I will think of how to implement a language selection system in the mean time. I would like to keep it easy to use, maybe add an enumerated value for language as an input to .TestAndScore(). This way user-specific messages can be provided. I would also like to provide the ability to supply error messages.

I should have something together for this in the next few days.

**Comment by UweKeim** [comment]
Awesome! 

I would suggest to simply [rely on standard RESX string resources](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) (you know those "`Resources.resx`", "`Resources.de.resx`", "`Resources.fr.resx`", etc.), you could take a look at my free [Zeta Resource Editor](https://www.zeta-resource-editor.com/) tool which helps in translating between RESX files.

So basically simply extract all the resources to a RESX file, I will happily provide a high-quality German translation for all English texts.

**Comment by thirstyape** [comment]
Excellent, thank you for pointing me in the right direction. I agree the RESX system is the way to go.

**Comment by thirstyape** [comment]
Ok, I have created a new branch that has Resources.resx and Resources.de.resx added. 

I will be using something such as `Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo(languageCode);` within the .TestAndScore() method to allow user-specific language settings. This is so server based applications can still use multiple translations.

Whenever you have German translations for the error messages I will add them to the .de.resx file

**Comment by UweKeim** [comment]
Please find attached the translated file:

> [Easy-Password-Validator.zip](https://github.com/thirstyape/Easy-Password-Validator/files/5515064/Easy-Password-Validator.zip)

(I've included the project file for my Zeta Resource Editor).

I've also slightly adjusted your English resource file:

- Added full stops at the end of each message (this is something that Microsoft recommends)
- Made the error messages more similar to each other.

Feel free to use or discard my English adjustments. 😊.

For the German translations, I've used the official translation in the Microsoft Language Portal, e.g. [for this term](https://www.microsoft.com/en-us/language/Search?&searchTerm=Bad%20password&langID=354&Source=true&productid=0). Hope you like it.

Thanks for your quick adjustments, very appreciated.
