### ISSUE TITLE
Add an option for checking the Shannon Entropy

### ISSUE THREAD

**Issue by UweKeim** [thirstyape/Easy-Password-Validator#2]
This is a code of mine I'm using for a long time to check whether passwords are complex enough:

```csharp
/// <summary>
/// returns bits of entropy represented in a given string, per 
/// http://en.wikipedia.org/wiki/Entropy_(information_theory) 
/// 
/// https://codereview.stackexchange.com/a/909/1996
/// </summary>
/// <returns>
/// "abcdefghijklmnop" = 4.00
/// "Hello, World!" = 3.18
/// "hello world" = 2.85
/// "123123123123" = 1.58
/// "aaaa" = 0
/// </returns>
private static double ShannonEntropy(string s)
{
    var map = new Dictionary<char, int>();
    foreach (var c in s)
    {
        if (!map.ContainsKey(c))
            map.Add(c, 1);
        else
            map[c] += 1;
    }

    var result = 0.0;
    var len = s.Length;
    foreach (var item in map)
    {
        var frequency = (double) item.Value / len;
        result -= frequency * (Math.Log(frequency) / Math.Log(2));
    }

    return result;
}
```

I would suggest to add this to your library, including an option in the [`PasswordRequirements` class](https://github.com/thirstyape/Easy-Password-Validator/blob/master/Models/PasswordRequirements.cs) to configure the entropy.

E.g.:

```csharp
 public float MinEntropy { get; set; } = 3.0f;
```

**Comment by thirstyape** [comment]
Looks like a good addition, I will be focusing on the other issue you opened first as this can be accomplished already by using IPasswordTest, IPasswordRequirements, and .AddTest()

**Comment by thirstyape** [comment]
Finally have some time to get around to this, I'll have a commit posted in a bit. 

@UweKeim can you provide a translation for the following?

`Password must have entropy score of at least {0}.`

**Comment by UweKeim** [comment]
I would translate it as:

```
Das Kennwort muss einen Entropie-Wert von mindestens {0} haben.
```

Thanks for constantly improving your awesome library!

**Comment by thirstyape** [comment]
Added a [branch](https://github.com/thirstyape/Easy-Password-Validator/tree/2-add-entropy-tester) for this issue.

Not sure yet on how to modify score based on entropy or whether it should be done as it may cause problems for anyone upgrading to the latest version (i.e. if someone has configured score thresholds they will require adjustment).

**Comment by UweKeim** [comment]
How about adding it as an additional option. 

I.e. a boolean that configured whether robust entropy at all, and one float option with the actual minimum entropy required. Default of the boolean is false, so no change for upgraders.
