### ISSUE TITLE
.NET Standard 2.0 compatibility

### ISSUE THREAD

**Issue by dlandi** [thirstyape/Easy-Password-Validator#3]
Hi. You only use switch expressions in two places which makes the codebase incompatible with .NET Standard 2.0.

I've made the changes and added multi-targeting to the project file.

Please add me as a developer so I can upload a put request.

**Comment by thirstyape** [comment]
Hi @dlandi , 

It is more than just the switch expressions; but I agree that adding support for .NET Standard 2.0 is a good idea so as to enable use with .NET Framework.

Working on an update now.

**Comment by thirstyape** [comment]
Done
