### ISSUE TITLE
NullReferenceException for simple password-check in v1.2.1

### ISSUE THREAD

**Issue by johannes-steurer** [thirstyape/Easy-Password-Validator#4]
Hi,

the following code started to throw a NullReferenceException after updating from 1.1.8 to 1.2.1.

```
var requirements = new PasswordRequirements()
        {
            MinLength = 8,
            RequireDigit = true,
            RequireLowercase = true,
            RequireUppercase = true,
            RequirePunctuation = true,
            MaxNeighboringCharacter = 99,
            MinScore = 0,
            MaxRepeatSameCharacter = 99,
            MinEntropy = 0,
        };

var passwordValidator = new PasswordValidatorService(requirements);

var pass = passwordValidator.TestAndScore(password); // throws Exception
```

I just want to have a local password-check without usage of the bad-list, but according to the stack-trace it is looking up the BadList Settings withch is null (the Settings Porperty)
![grafik](https://github.com/thirstyape/Easy-Password-Validator/assets/93578472/49c69451-01d7-4638-ab33-13a62158cf0f)

I already tried to set the back-list paramter to false but it does not help

**Comment by johannes-steurer** [comment]
Thanks for the quick answer. 
Looking forward to the new version ;)

**Comment by thirstyape** [comment]
Also added an xUnit testing project, so this type of thing should be less likely going forwards.
